### PR TITLE
120 loosing data when crashes

### LINKED ISSUE #120: losing data when app stops
Sometimes when the app crashes or shuts down prematurely the data is not able to be saved to the disk. Causing the database and the hash table to not contain matching information. This can be solved by running a task in the background every once in a while to save the hash table.

### LINKED ISSUE #134: datasync merge fix
A block of code was missed in commit: https://github.com/MarshallAsch/veil-droid/commit/d72a5297a9d4723019bdd6bbeda92ba1f2beb4d8

- MainActivity.java lines 232 - 238
- Adding them back in will potentially fix the data sync issue

### PR DESCRIPTION
**Pull request by MarshallAsch**
closes #120. closes #134. Reduces the the data lost when the device crashes by more frequently saving the data store to a file. Various other small fixes.

### CODE REVIEW

File: app/src/main/java/ca/marshallasch/veil/DataStore.java [hunk 1]
```diff
@@ -417,5 +424,30 @@ public void insertSync(@Nullable Sync.SyncMessage syncMessage) {
             db.insertKnownPost(entry.getPostHash(), entry.getCommentHash());
         }
 
+        hashTableStore.save();
+    }
+
+    /**
+     * This task will be run every 10 minutes to try to save the has table store if it has been modified.
```
Comment (weihanli101) [inline app/src/main/java/ca/marshallasch/veil/DataStore.java]: How costly is this?

File: app/src/main/java/ca/marshallasch/veil/HashTableStore.java [hunk 2]
```diff
@@ -103,17 +110,18 @@ public static synchronized HashTableStore getInstance(@Nullable final Context c)
...
-    public void save(@Nullable Context context) {
+    public void save() {
 
-        // if there is no context then don't save the file
-        if (context == null) {
+        // if the file does not exist then do not save, or if it has not been modified
+        if (mapFile == null || !modified) {
+            Log.d("HashTableStore", "Not actually saving the file, changed: " + String.valueOf(modified));
             return;
         }
```
Comment (weihanli101) [inline app/src/main/java/ca/marshallasch/veil/HashTableStore.java]: Why was this `File mapFile = new File(context.getFilesDir(), "HASH_MAP");` deleted. Its later called in the try block below.

Comment (MarshallAsch) [reply app/src/main/java/ca/marshallasch/veil/HashTableStore.java]: The file is now created in the constructor instead of in the save function
