### PR TITLE
fixed issue where logout button retained the backstack causing unwant…

### LINKED ISSUE #37: logout button routes to wrong fragment
The logout button currently pops fragments off the back stack. This causes it to route to the wrong fragments.

### PR DESCRIPTION
**Pull request by weihanli101**
this closes #37

### CODE REVIEW

File: app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java [hunk 1]
```diff
@@ -72,7 +72,8 @@ public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup c
         });
 
         done.setOnClickListener(v ->{
-            this.onDoneClicked(v);
+            //route to login after sign up
```
Comment (MarshallAsch) [inline app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java]: You just got rid of all of the sign up logic.

Comment (MarshallAsch) [reply app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java]: Fixed in 15ec8c.
